export const movies = [
  {
    title: "Hum Aapke Hain Kaun!",
    image: "https://upload.wikimedia.org/wikipedia/en/7/79/Hahk.jpg",
    desc: `Prem (Salman Khan) lost his parents at an early age. He lives with his elder brother Rajesh (Mohnish Bahl) and uncle Kailashnath (Alok Nath). Rajesh manages the family business and his family is on the look-out for a suitable bride for him. Professor Siddharth Chaudhary (Anupam Kher) and Mrs. Chaudhary (Reema Lagoo) have two daughters, Pooja (Renuka Shahane) and Nisha (Madhuri Dixit). The Chaudhary couple and Kailashnath are old friends who meet again after several years. They arrange a marriage between Rajesh and Pooja. From their first meeting, Nisha and Prem start bickering lightheartedly with each other, and the fun and mischief continues throughout Pooja and Rajesh's wedding.
    
    Prem has an amicable relationship with his warm-hearted sister-in-law. In time, Pooja and Rajesh discover that they are expecting a child. Professor and Mrs. Chaudhary were unable to come to Kailashnath's house for the ceremony marking the impending arrival of the baby. They send Nisha instead, who is present at the birth. Meanwhile, Nisha and Prem fall in love with each other, but keep it a secret. Professor and Mrs. Chaudhary come over to Kailashnath's house to celebrate the birth of their grandchild. When the time comes to part, their hosts are dejected, especially Prem. He and Nisha promise each other that they will soon reunite for ever.
    
    Pooja is invited to stay at her parents' house, and Prem takes her there. When they arrive, Pooja learns that Prem and Nisha are in love, and gives Nisha a necklace as a token, promising to get them married. Shortly afterwards, Pooja accidentally slips and falls down the stairs, and dies from a head injury. Everybody is shattered by the tragedy.
    
    Nisha takes good care of her sister's son. Hence, her parents and Kailashnath feel that Nisha will be a great mother to the baby. They decide to have Nisha marry Rajesh. Nisha overhears her parents talking about her marrying into Kailashnath's family and thinks that they are discussing her marriage to Prem, to which she agrees. Later, at a pre-nuptial ceremony, she finds out that she is actually going to marry Rajesh.
    
    Prem and Nisha vow to sacrifice their love for Rajesh and the baby. Moments before the wedding, Nisha asks Prem's dog Tuffy to give Prem the necklace that Pooja had given her, along with a letter. Tuffy exits Nisha's room and instead of taking the letter to Prem, delivers it to Rajesh. Rajesh reads the letter and realizes that Prem and Nisha love each other. Subsequently, he halts the wedding and confronts both Nisha and Prem. In the end, Nisha and Prem marry each other with the consent of their families.`
  }
]